### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by Francis-Young** [YANG-ERA/GraphPCA#1]
Hello, I recently read your GraphPCA paper and was thoroughly impressed by your research and findings. The insights provided are incredibly valuable.

However, while following the tutorial provided: https://graphpca-analyses.readthedocs.io/en/latest/Tutorial1_DLPFC.html , I encountered difficulties in locating the corresponding data as per the instructions. Despite my best efforts, I was unable to find the necessary datasets to proceed with the experiments.

Could you kindly provide the following data needed in Tutorial 1:

1. sample_data in h5ad format
2. groundtruth data
3. SVG_list data

Your assistance in this matter would be greatly appreciated. Thank you for your time and consideration. 
My email is yangfanb2581@163.com

**Comment by YANG-ERA** [comment]
Dear Young,

Thank you for your kind words regarding our GraphPCA paper. I'm delighted to hear that you found the research and findings valuable.

I understand that you are experiencing difficulties in locating the necessary datasets for Tutorial 1. We have organized the specific files you mentioned—sample_data in h5ad format, groundtruth data, and SVG_list data—and they can be accessed at the following link:

[GraphPCA_analysis - Google Drive](https://drive.google.com/drive/folders/1Sjbb8BejjPG-FIsk3d-I5vMAbCAvPrH6?usp=sharing)

Note that the DLPFC raw data is too large! You can visit https://github.com/LieberInstitute/spatialLIBD to download the DLPFC data directly.
In addition, the sample data-making process is the same as the SpaGCN tutorial (https://github.com/jianhuupenn/SpaGCN/blob/master/tutorial/tutorial.md).

I hope this will enable you to successfully perform the algorithm outlined in our tutorial. If you have any further questions or need additional assistance, please feel free to reach out.

Best regards

**Comment by Francis-Young** [comment]
Dear YANG,

Thank you very much for providing the data, they are extremely helpful. I am grateful for your prompt assistant and generosity in sharing these resources.

Best regards
